import { ExerciseType, PrismaClient } from "@/generated/prisma/client";

// Maps exercise category slug -> category DB id (from categories.seed.ts)
const categoryIdMap: Record<string, string> = {
  chest: "cmov3v5m9000504l46masghow",
  back: "hyxmbll9m62xav4fpug1y9pb",
  shoulders: "ucwdnlo2iqovjp1dsrbvtrqz",
  legs: "dt88glpys1euy66mcwquozrh",
  biceps: "h9cozxu26wx1amos66ygxn38",
  triceps: "ngwai6jas7vmzttctl1pm3tk",
  core: "k4xwcozyrepfyvyoiixgaa32",
};

type ExerciseData = {
  slug: string;
  nameEs: string;
  nameEn: string;
  type: ExerciseType;
  categorySlug: string;
  equipmentSlugs: string[];
  primaryMuscleSlugs: string[];
  secondaryMuscleSlugs: string[];
};

const exercises: ExerciseData[] = [
  // ── Chest ────────────────────────────────────────────────────────────────
  {
    slug: "bench_press_barbell",
    nameEs: "Press de banca con barra",
    nameEn: "Barbell Bench Press",
    type: ExerciseType.COMPOUND,
    categorySlug: "chest",
    equipmentSlugs: ["barbell", "bench"],
    primaryMuscleSlugs: ["pectorals"],
    secondaryMuscleSlugs: ["triceps", "front_deltoids"],
  },
  {
    slug: "bench_press_dumbbell",
    nameEs: "Press de banca con mancuernas",
    nameEn: "Dumbbell Bench Press",
    type: ExerciseType.COMPOUND,
    categorySlug: "chest",
    equipmentSlugs: ["dumbbells", "bench"],
    primaryMuscleSlugs: ["pectorals"],
    secondaryMuscleSlugs: ["triceps", "front_deltoids"],
  },
  {
    slug: "incline_bench_press",
    nameEs: "Press inclinado con barra",
    nameEn: "Incline Barbell Bench Press",
    type: ExerciseType.COMPOUND,
    categorySlug: "chest",
    equipmentSlugs: ["barbell", "incline_bench"],
    primaryMuscleSlugs: ["upper_pectorals"],
    secondaryMuscleSlugs: ["triceps", "front_deltoids"],
  },
  {
    slug: "push_up",
    nameEs: "Flexiones (push-ups)",
    nameEn: "Push-up",
    type: ExerciseType.COMPOUND,
    categorySlug: "chest",
    equipmentSlugs: [],
    primaryMuscleSlugs: ["pectorals"],
    secondaryMuscleSlugs: ["triceps", "front_deltoids", "core"],
  },
  {
    slug: "chest_dip",
    nameEs: "Fondos en paralelas (pecho)",
    nameEn: "Chest Dip",
    type: ExerciseType.COMPOUND,
    categorySlug: "chest",
    equipmentSlugs: ["parallel_bars"],
    primaryMuscleSlugs: ["lower_pectorals"],
    secondaryMuscleSlugs: ["triceps", "front_deltoids"],
  },
  {
    slug: "cable_fly",
    nameEs: "Aperturas en polea",
    nameEn: "Cable Fly",
    type: ExerciseType.ISOLATED,
    categorySlug: "chest",
    equipmentSlugs: ["cables"],
    primaryMuscleSlugs: ["pectorals"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "pec_deck",
    nameEs: "Aperturas en máquina (pec deck)",
    nameEn: "Pec Deck",
    type: ExerciseType.ISOLATED,
    categorySlug: "chest",
    equipmentSlugs: ["chest_machine"],
    primaryMuscleSlugs: ["pectorals"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "dumbbell_pullover",
    nameEs: "Pull-over con mancuerna",
    nameEn: "Dumbbell Pullover",
    type: ExerciseType.COMPOUND,
    categorySlug: "chest",
    equipmentSlugs: ["dumbbell", "bench"],
    primaryMuscleSlugs: ["pectorals"],
    secondaryMuscleSlugs: ["lats"],
  },
  // ── Back ─────────────────────────────────────────────────────────────────
  {
    slug: "pull_up",
    nameEs: "Dominadas (agarre prono)",
    nameEn: "Pull-up",
    type: ExerciseType.COMPOUND,
    categorySlug: "back",
    equipmentSlugs: ["pull_up_bar"],
    primaryMuscleSlugs: ["lats"],
    secondaryMuscleSlugs: ["biceps", "traps", "core"],
  },
  {
    slug: "chin_up",
    nameEs: "Dominadas supinas (chin-ups)",
    nameEn: "Chin-up",
    type: ExerciseType.COMPOUND,
    categorySlug: "back",
    equipmentSlugs: ["pull_up_bar"],
    primaryMuscleSlugs: ["lats"],
    secondaryMuscleSlugs: ["biceps"],
  },
  {
    slug: "barbell_row",
    nameEs: "Remo con barra",
    nameEn: "Barbell Row",
    type: ExerciseType.COMPOUND,
    categorySlug: "back",
    equipmentSlugs: ["barbell"],
    primaryMuscleSlugs: ["lats", "rhomboids"],
    secondaryMuscleSlugs: ["biceps", "core"],
  },
  {
    slug: "t_bar_row",
    nameEs: "Remo en T",
    nameEn: "T-Bar Row",
    type: ExerciseType.COMPOUND,
    categorySlug: "back",
    equipmentSlugs: ["t_bar_row_machine"],
    primaryMuscleSlugs: ["lats", "rhomboids"],
    secondaryMuscleSlugs: ["biceps"],
  },
  {
    slug: "seated_cable_row",
    nameEs: "Remo en polea sentado",
    nameEn: "Seated Cable Row",
    type: ExerciseType.COMPOUND,
    categorySlug: "back",
    equipmentSlugs: ["cable"],
    primaryMuscleSlugs: ["lats", "rhomboids"],
    secondaryMuscleSlugs: ["biceps"],
  },
  {
    slug: "lat_pulldown",
    nameEs: "Jalón al pecho (lat pulldown)",
    nameEn: "Lat Pulldown",
    type: ExerciseType.COMPOUND,
    categorySlug: "back",
    equipmentSlugs: ["lat_pulldown_machine"],
    primaryMuscleSlugs: ["lats"],
    secondaryMuscleSlugs: ["biceps", "traps"],
  },
  {
    slug: "deadlift_conventional",
    nameEs: "Peso muerto convencional",
    nameEn: "Conventional Deadlift",
    type: ExerciseType.COMPOUND,
    categorySlug: "back",
    equipmentSlugs: ["barbell"],
    primaryMuscleSlugs: ["posterior_chain", "glutes", "hamstrings"],
    secondaryMuscleSlugs: ["lower_back", "traps"],
  },
  {
    slug: "deadlift_romanian",
    nameEs: "Peso muerto rumano",
    nameEn: "Romanian Deadlift",
    type: ExerciseType.COMPOUND,
    categorySlug: "back",
    equipmentSlugs: ["barbell"],
    primaryMuscleSlugs: ["hamstrings"],
    secondaryMuscleSlugs: ["glutes", "lower_back"],
  },
  {
    slug: "reverse_fly",
    nameEs: "Aperturas invertidas (remo pájaro)",
    nameEn: "Reverse Fly",
    type: ExerciseType.ISOLATED,
    categorySlug: "back",
    equipmentSlugs: ["dumbbells", "machine"],
    primaryMuscleSlugs: ["rear_deltoids"],
    secondaryMuscleSlugs: ["mid_traps"],
  },
  // ── Shoulders ────────────────────────────────────────────────────────────
  {
    slug: "overhead_press_barbell",
    nameEs: "Press militar con barra",
    nameEn: "Barbell Overhead Press",
    type: ExerciseType.COMPOUND,
    categorySlug: "shoulders",
    equipmentSlugs: ["barbell"],
    primaryMuscleSlugs: ["deltoids"],
    secondaryMuscleSlugs: ["triceps", "traps"],
  },
  {
    slug: "overhead_press_dumbbell",
    nameEs: "Press militar con mancuernas",
    nameEn: "Dumbbell Overhead Press",
    type: ExerciseType.COMPOUND,
    categorySlug: "shoulders",
    equipmentSlugs: ["dumbbells"],
    primaryMuscleSlugs: ["deltoids"],
    secondaryMuscleSlugs: ["triceps"],
  },
  {
    slug: "arnold_press",
    nameEs: "Press Arnold",
    nameEn: "Arnold Press",
    type: ExerciseType.COMPOUND,
    categorySlug: "shoulders",
    equipmentSlugs: ["dumbbells"],
    primaryMuscleSlugs: ["deltoids"],
    secondaryMuscleSlugs: ["triceps"],
  },
  {
    slug: "lateral_raise",
    nameEs: "Elevaciones laterales",
    nameEn: "Lateral Raise",
    type: ExerciseType.ISOLATED,
    categorySlug: "shoulders",
    equipmentSlugs: ["dumbbells", "cable"],
    primaryMuscleSlugs: ["lateral_deltoids"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "front_raise",
    nameEs: "Elevaciones frontales",
    nameEn: "Front Raise",
    type: ExerciseType.ISOLATED,
    categorySlug: "shoulders",
    equipmentSlugs: ["dumbbells", "weight_plate"],
    primaryMuscleSlugs: ["front_deltoids"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "rear_delt_fly",
    nameEs: "Aperturas deltoide posterior",
    nameEn: "Rear Delt Fly",
    type: ExerciseType.ISOLATED,
    categorySlug: "shoulders",
    equipmentSlugs: ["dumbbells", "machine", "cable"],
    primaryMuscleSlugs: ["rear_deltoids"],
    secondaryMuscleSlugs: ["traps"],
  },
  {
    slug: "face_pull",
    nameEs: "Face pulls en polea",
    nameEn: "Face Pull",
    type: ExerciseType.ISOLATED,
    categorySlug: "shoulders",
    equipmentSlugs: ["cable"],
    primaryMuscleSlugs: ["rear_deltoids"],
    secondaryMuscleSlugs: ["traps", "rhomboids"],
  },
  // ── Legs ─────────────────────────────────────────────────────────────────
  {
    slug: "back_squat",
    nameEs: "Sentadilla trasera con barra",
    nameEn: "Back Squat",
    type: ExerciseType.COMPOUND,
    categorySlug: "legs",
    equipmentSlugs: ["barbell", "rack"],
    primaryMuscleSlugs: ["quadriceps", "glutes"],
    secondaryMuscleSlugs: ["hamstrings", "core"],
  },
  {
    slug: "front_squat",
    nameEs: "Sentadilla frontal",
    nameEn: "Front Squat",
    type: ExerciseType.COMPOUND,
    categorySlug: "legs",
    equipmentSlugs: ["barbell", "rack"],
    primaryMuscleSlugs: ["quadriceps"],
    secondaryMuscleSlugs: ["glutes", "core"],
  },
  {
    slug: "leg_press",
    nameEs: "Prensa de pierna",
    nameEn: "Leg Press",
    type: ExerciseType.COMPOUND,
    categorySlug: "legs",
    equipmentSlugs: ["leg_press_machine"],
    primaryMuscleSlugs: ["quadriceps"],
    secondaryMuscleSlugs: ["glutes", "hamstrings"],
  },
  {
    slug: "lunge_dumbbell",
    nameEs: "Zancadas con mancuernas",
    nameEn: "Dumbbell Lunge",
    type: ExerciseType.COMPOUND,
    categorySlug: "legs",
    equipmentSlugs: ["dumbbells"],
    primaryMuscleSlugs: ["quadriceps", "glutes"],
    secondaryMuscleSlugs: ["hamstrings"],
  },
  {
    slug: "bulgarian_split_squat",
    nameEs: "Sentadilla búlgara",
    nameEn: "Bulgarian Split Squat",
    type: ExerciseType.COMPOUND,
    categorySlug: "legs",
    equipmentSlugs: ["bench", "dumbbells"],
    primaryMuscleSlugs: ["quadriceps", "glutes"],
    secondaryMuscleSlugs: ["core"],
  },
  {
    slug: "romanian_deadlift",
    nameEs: "Peso muerto rumano",
    nameEn: "Romanian Deadlift",
    type: ExerciseType.COMPOUND,
    categorySlug: "legs",
    equipmentSlugs: ["barbell", "dumbbells"],
    primaryMuscleSlugs: ["hamstrings"],
    secondaryMuscleSlugs: ["glutes", "lower_back"],
  },
  {
    slug: "leg_curl_machine",
    nameEs: "Curl femoral en máquina",
    nameEn: "Leg Curl Machine",
    type: ExerciseType.ISOLATED,
    categorySlug: "legs",
    equipmentSlugs: ["leg_curl_machine"],
    primaryMuscleSlugs: ["hamstrings"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "leg_extension",
    nameEs: "Extensiones de cuadríceps",
    nameEn: "Leg Extension",
    type: ExerciseType.ISOLATED,
    categorySlug: "legs",
    equipmentSlugs: ["leg_extension_machine"],
    primaryMuscleSlugs: ["quadriceps"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "hip_thrust_barbell",
    nameEs: "Hip thrust con barra",
    nameEn: "Barbell Hip Thrust",
    type: ExerciseType.COMPOUND,
    categorySlug: "legs",
    equipmentSlugs: ["barbell", "bench"],
    primaryMuscleSlugs: ["glutes"],
    secondaryMuscleSlugs: ["hamstrings"],
  },
  {
    slug: "calf_raise_standing",
    nameEs: "Elevaciones de talón de pie",
    nameEn: "Standing Calf Raise",
    type: ExerciseType.ISOLATED,
    categorySlug: "legs",
    equipmentSlugs: ["machine", "dumbbells"],
    primaryMuscleSlugs: ["calves"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "calf_raise_seated",
    nameEs: "Elevaciones de talón sentado",
    nameEn: "Seated Calf Raise",
    type: ExerciseType.ISOLATED,
    categorySlug: "legs",
    equipmentSlugs: ["seated_calf_machine"],
    primaryMuscleSlugs: ["soleus"],
    secondaryMuscleSlugs: [],
  },
  // ── Biceps ───────────────────────────────────────────────────────────────
  {
    slug: "barbell_curl",
    nameEs: "Curl de bíceps con barra",
    nameEn: "Barbell Curl",
    type: ExerciseType.ISOLATED,
    categorySlug: "biceps",
    equipmentSlugs: ["barbell"],
    primaryMuscleSlugs: ["biceps"],
    secondaryMuscleSlugs: ["forearms"],
  },
  {
    slug: "dumbbell_curl",
    nameEs: "Curl de bíceps con mancuernas",
    nameEn: "Dumbbell Curl",
    type: ExerciseType.ISOLATED,
    categorySlug: "biceps",
    equipmentSlugs: ["dumbbells"],
    primaryMuscleSlugs: ["biceps"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "hammer_curl",
    nameEs: "Curl martillo",
    nameEn: "Hammer Curl",
    type: ExerciseType.ISOLATED,
    categorySlug: "biceps",
    equipmentSlugs: ["dumbbells"],
    primaryMuscleSlugs: ["brachialis"],
    secondaryMuscleSlugs: ["forearms"],
  },
  {
    slug: "preacher_curl",
    nameEs: "Curl en banco predicador",
    nameEn: "Preacher Curl",
    type: ExerciseType.ISOLATED,
    categorySlug: "biceps",
    equipmentSlugs: ["ez_bar", "preacher_bench"],
    primaryMuscleSlugs: ["biceps"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "concentration_curl",
    nameEs: "Curl de concentración",
    nameEn: "Concentration Curl",
    type: ExerciseType.ISOLATED,
    categorySlug: "biceps",
    equipmentSlugs: ["dumbbell"],
    primaryMuscleSlugs: ["biceps"],
    secondaryMuscleSlugs: [],
  },
  // ── Triceps ───────────────────────────────────────────────────────────────
  {
    slug: "close_grip_bench_press",
    nameEs: "Press de banca agarre cerrado",
    nameEn: "Close-Grip Bench Press",
    type: ExerciseType.COMPOUND,
    categorySlug: "triceps",
    equipmentSlugs: ["barbell", "bench"],
    primaryMuscleSlugs: ["triceps"],
    secondaryMuscleSlugs: ["pectorals", "front_deltoids"],
  },
  {
    slug: "parallel_dip_triceps",
    nameEs: "Fondos en paralelas (tríceps)",
    nameEn: "Triceps Dip",
    type: ExerciseType.COMPOUND,
    categorySlug: "triceps",
    equipmentSlugs: ["parallel_bars"],
    primaryMuscleSlugs: ["triceps"],
    secondaryMuscleSlugs: ["pectorals"],
  },
  {
    slug: "overhead_triceps_extension_dumbbell",
    nameEs: "Extensión de tríceps por encima de la cabeza",
    nameEn: "Overhead Triceps Extension",
    type: ExerciseType.ISOLATED,
    categorySlug: "triceps",
    equipmentSlugs: ["dumbbell", "ez_bar"],
    primaryMuscleSlugs: ["triceps"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "skull_crusher",
    nameEs: "Rompecráneos con barra Z",
    nameEn: "Skull Crusher",
    type: ExerciseType.ISOLATED,
    categorySlug: "triceps",
    equipmentSlugs: ["ez_bar", "bench"],
    primaryMuscleSlugs: ["triceps"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "triceps_pushdown_cable",
    nameEs: "Jalón de tríceps en polea",
    nameEn: "Triceps Pushdown",
    type: ExerciseType.ISOLATED,
    categorySlug: "triceps",
    equipmentSlugs: ["cable"],
    primaryMuscleSlugs: ["triceps"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "triceps_kickback",
    nameEs: "Patada de tríceps con mancuerna",
    nameEn: "Triceps Kickback",
    type: ExerciseType.ISOLATED,
    categorySlug: "triceps",
    equipmentSlugs: ["dumbbells"],
    primaryMuscleSlugs: ["triceps"],
    secondaryMuscleSlugs: [],
  },
  // ── Core ─────────────────────────────────────────────────────────────────
  {
    slug: "plank",
    nameEs: "Plancha",
    nameEn: "Plank",
    type: ExerciseType.COMPOUND,
    categorySlug: "core",
    equipmentSlugs: [],
    primaryMuscleSlugs: ["abs"],
    secondaryMuscleSlugs: ["deep_core", "shoulders"],
  },
  {
    slug: "side_plank",
    nameEs: "Plancha lateral",
    nameEn: "Side Plank",
    type: ExerciseType.COMPOUND,
    categorySlug: "core",
    equipmentSlugs: [],
    primaryMuscleSlugs: ["obliques"],
    secondaryMuscleSlugs: ["core"],
  },
  {
    slug: "hanging_leg_raise",
    nameEs: "Elevaciones de piernas colgado",
    nameEn: "Hanging Leg Raise",
    type: ExerciseType.ISOLATED,
    categorySlug: "core",
    equipmentSlugs: ["pull_up_bar"],
    primaryMuscleSlugs: ["lower_abs"],
    secondaryMuscleSlugs: ["hip_flexors"],
  },
  {
    slug: "crunch",
    nameEs: "Crunch abdominal",
    nameEn: "Crunch",
    type: ExerciseType.ISOLATED,
    categorySlug: "core",
    equipmentSlugs: [],
    primaryMuscleSlugs: ["abs"],
    secondaryMuscleSlugs: [],
  },
  {
    slug: "russian_twist",
    nameEs: "Giros rusos",
    nameEn: "Russian Twist",
    type: ExerciseType.ISOLATED,
    categorySlug: "core",
    equipmentSlugs: ["weight_plate", "dumbbell"],
    primaryMuscleSlugs: ["obliques"],
    secondaryMuscleSlugs: ["abs"],
  },
  {
    slug: "ab_rollout_wheel",
    nameEs: "Rodillo abdominal",
    nameEn: "Ab Wheel Rollout",
    type: ExerciseType.COMPOUND,
    categorySlug: "core",
    equipmentSlugs: ["ab_wheel"],
    primaryMuscleSlugs: ["abs"],
    secondaryMuscleSlugs: ["deep_core", "shoulders"],
  },
  {
    slug: "cable_woodchopper",
    nameEs: "Giro en polea (woodchopper)",
    nameEn: "Cable Woodchopper",
    type: ExerciseType.ISOLATED,
    categorySlug: "core",
    equipmentSlugs: ["cable"],
    primaryMuscleSlugs: ["obliques"],
    secondaryMuscleSlugs: ["abs"],
  },
  {
    slug: "mountain_climber",
    nameEs: "Escaladores",
    nameEn: "Mountain Climber",
    type: ExerciseType.COMPOUND,
    categorySlug: "core",
    equipmentSlugs: [],
    primaryMuscleSlugs: ["abs"],
    secondaryMuscleSlugs: ["shoulders", "hips"],
  },
];

export async function seedExercises(prisma: PrismaClient) {
  for (const exercise of exercises) {
    const categoryId = categoryIdMap[exercise.categorySlug];
    if (!categoryId) {
      console.warn(
        `Skipping exercise "${exercise.slug}" — no category ID for: ${exercise.categorySlug}`,
      );
      continue;
    }

    const equipmentConnect = exercise.equipmentSlugs.map((slug) => ({ slug }));
    const primaryMuscleConnect = exercise.primaryMuscleSlugs.map((slug) => ({
      slug,
    }));
    const secondaryMuscleConnect = exercise.secondaryMuscleSlugs.map(
      (slug) => ({ slug }),
    );

    await prisma.exercise.upsert({
      where: { slug: exercise.slug },
      update: {
        nameEs: exercise.nameEs,
        nameEn: exercise.nameEn,
        type: exercise.type,
        equipments: { set: equipmentConnect },
        primaryMuscles: { set: primaryMuscleConnect },
        secondaryMuscles: { set: secondaryMuscleConnect },
      },
      create: {
        slug: exercise.slug,
        nameEs: exercise.nameEs,
        nameEn: exercise.nameEn,
        type: exercise.type,
        categoryId,
        equipments: { connect: equipmentConnect },
        primaryMuscles: { connect: primaryMuscleConnect },
        secondaryMuscles: { connect: secondaryMuscleConnect },
      },
    });
  }
}
